.github/workflows/stage.yaml

Should be `=`, not `==`. 
When running the stage.yml workflow, I see:
```
/home/runner/work/_temp/b6973b0b-905e-4409-a600-a3a2227b69f2.sh: line 8: conditional binary operator expected
```

Fix conditional check for version input on stage workflow

---

.ci/scripts/generate-cal-version.py
.github/workflows/stage.yaml

GHA  took issue with me running this as an in-line script, giving me the following error:
```
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/346.
```
My best guess is that it is stumbling over the python import lines because of a name conflict with "import" and whatever tool GHA uses to run workflows in containers.  
So I am breaking the script out into a dedicated file as it should have been in the first place. 
I also improved the script to error if the input_version from the user is already a release.
This passes all of my test cases below:
```bash
$ GH_REPO=ansible/galaxy-operator INPUT_VERSION='0.15.0' python3 generate-cal-version.py
Traceback (most recent call last):
File "/home/chadams/galaxy-operator/.ci/scripts/generate-cal-version.py", line 12, in …
```

Break calver generation into a dedicated python script

---

README.md

The README and readthedocs were having trouble resolving the image from the same location so to avoid this I just set the full url path in the README which SHOULD work everywhere.

setting README image source to full url

---

mkdocs.yaml

As follow-up for #69, this PR enables search feature by using built-in `search` plugin from Material theme.
@aknochow 
F.Y.I., [just adding `search.*` to `features`](https://github.com/ansible/galaxy-operator/pull/69/files#diff-57381c8acc17df6530456c578e76d03d4a1cb287f7edd980502b4a9cedb9524dR18-R20) is not enough to enable search feature. 
Please refer to my comment on the PR on AWX Operator repo to further information for the changes I made in this PR: https://github.com/ansible/awx-operator/pull/1725#discussion_r1498621721
See also: https://github.com/ansible/mkdocs-ansible/blob/main/mkdocs.yml

docs: enable search feature

---

roles/galaxy-web/templates/galaxy-web.configmap.yaml.j2

Closes #74 
Add missing following two snippets for configmap for nginx.conf:
- `location /v2/` with `client_max_body_size 0;`
- `location /pulp/container/` with `proxy_pass http://galaxy-content;`
Tested by deploying customize Operator:
```bash
$ IMG=registry.example.com/ansible/galaxy-operator:nginx-v2 make docker-build docker-push deploy
```
After customized Operator is up and running, I can confirm `docker push` works as expeted.
```bash
$ docker push galaxy.example.com/ansible/awx-operator:latest
The push refers to repository [galaxy.example.com/ansible/awx-operator]
8a781877ae2d: Layer already exists 
50249f417f60: Layer already exists 
308817e4fc18: Layer already exists 
159f14b224e2: Layer already exists 
d4a2fce0f4ab: Layer already exists 
5be6a5d3fc93: Pushed 
e611347a452f: …
```

fix: add missing nginx snippets for pulp_container

---

roles/galaxy-web/defaults/main.yml
roles/galaxy-web/templates/galaxy-web.configmap.yaml.j2
roles/galaxy-web/templates/galaxy-web.deployment.yaml.j2

Closes #77, but if you have a better way, feel free to close this PR and open new one 😃 
Changes:
- Rename `upstream` directives; `galaxy-*` to `pulp-*`, to use snippets as they are
- Rename keys in configmap from `*_conf` to `*.conf` to simplify `volumes`
- Add following three snippets as dedicated keys for each files under the same configmap
- [galaxy_ng.conf](https://github.com/ansible/galaxy_ng/blob/master/galaxy_ng/app/webserver_snippets/nginx.conf)
- [pulp_ansible.conf](https://github.com/pulp/pulp_ansible/blob/main/pulp_ansible/app/webserver_snippets/nginx.conf)
- [pulp_container.conf](https://github.com/pulp/pulp_container/blob/main/pulp_container/app/webserver_snippets/nginx.conf)
- Mount above snippets under `/etc/nginx/default.d`
- Add `include` to main `nginx.conf` to include …

feat: add missing snippets for nginx

---

.ci/scripts/backup_and_restore.sh
.ci/scripts/galaxy_tests.sh

The recent pulp-cli 0.24.0 release seems to have broken CI
* https://pypi.org/project/pulp-cli/

Pin pulp-cli to 0.23.0 for CI temporarily

---

.github/workflows/ci.yml
.github/workflows/pr.yml

If CI takes longer than 30 minutes to run, there is probably an issue, we should fail early rather than wasting more GHA minutes.  This also has the added bonus of the logs not being so long that they don't load in the GitHub UI.

Set reasonable default GHA timeout values values

---

Makefile

When using podman as engine for pushing the catalog index then it's still using docker rather than the podman target
```
```

Makefile: Fix catalog-push with podman engine

---

config/samples/galaxy_v1beta1_galaxy_cr.ci.yaml

`main` tag does not exist on https://quay.io/repository/ansible/galaxy-ng?tab=tags&tag=latest

Remove invalid main image tags from samples

---

roles/galaxy-api/templates/galaxy-api.deployment.yaml.j2

There is a bug within one of the deployment templates where the `bundle_ca_crt` block is wrapped within the `is_file_storage` block. So in order for the `bundle_ca_crt` to occur, then `is_file_storage` needs to be false. I couldn't get this variable to be false on a normal deployment of Automation Hub.
```
{% if is_file_storage %}
- name: file-storage
readOnly: false
mountPath: "/var/lib/pulp"
{% else %}
- name: tmp-file-storage
mountPath: "/var/lib/pulp/tmp"
- name: assets-file-storage
mountPath: "/var/lib/pulp/assets"
{% if signing_secret is defined %}
- name: gpg-file-storage
mountPath: "/var/lib/pulp/.gnupg"
{% endif %}
{% if bundle_ca_crt is defined %}
- name: "ca-trust-extracted"
mountPath: "/etc/pki/ca-trust/extracted"
- name: "{{ ansible_operator_meta.name }}-bundle-cacert" …
```

fix: correct issue with bundle_cacert_secret in api template

---

.github/workflows/release.yaml

When running make bundle in the release.yaml GHA workflow, it fails with this error:
```
/home/runner/work/galaxy-operator/galaxy-operator/galaxy-operator/bin/operator-sdk: 1: Not: not found
```
This change will ensure that operator-sdk is installed for the following step.

Install operator-sdk for GHA

---

.ci/scripts/generate-cal-version.py

The release workflow currently fails because the calver version is not semver compatible:
```
Run make bundle bundle-build IMG=galaxy-operator:${TAG_NAME} VERSION=${TAG_NAME} BUNDLE_IMG=galaxy-operator-bundle:${TAG_NAME}
/usr/local/bin/operator-sdk generate kustomize manifests -q
cd config/manager && /usr/local/bin/kustomize edit set image controller=galaxy-operator:2024.04.03
/usr/local/bin/kustomize build config/manifests | /usr/local/bin/operator-sdk generate bundle -q --overwrite --version 2024.04.03 --channels="alpha" --default-channel="alpha"
Error: invalid command options: 2024.04.03 is not a valid semantic version: Minor number must not contain leading zeroes "04"
```
After this change, the leading zeros are gone and it is compatible.
```
$ GH_REPO=ansible/galaxy-operator python …
```

Make calver versions compatible with semver for bundle commands

---

.github/workflows/release.yaml

- engine defaults to podman, but podman does not support all docker buildx features at the moment
- for now, we can solve this by using docker everywhere in this workflow
- fix galaxy-operator image refs in CSV
tl;dr, there were a lot of issues with our promotion GHA workflow, they are now all resolved with this PR, evidenced by the successful release of 20.24.4.3:
* https://github.com/ansible/galaxy-operator/releases/tag/2024.4.3
* stage pipeline - https://github.com/ansible/galaxy-operator/actions/runs/8546049172
* promote pipeline - https://github.com/ansible/galaxy-operator/actions/runs/8557642616

Use docker engine for container build make targets in release GHA

---

roles/restore/tasks/postgres.yml

The current storage_claim fact is set in the block when the database is managed by the operator but that variable is used for the file storage PVC.
When using an external database then that fact isn't set and the next block statement about the PVC information fails
This was introduced during the backup/restore refact in 4ca8436e
```
TASK [Wait for PVC to be created if file-storage is used] ********************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'storage_claim' is undefined\n\nThe error appears to be in '/opt/ansible/roles/restore/tasks/postgres.yml': line 68, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n- block:\n - name: …
```

restore: Move storage_claim fact

---

config/default/kustomization.yaml

when trying to deploy the operator on a k3s instance I was getting an error saying "patchesStrategicMerge is deprecated. Please use patches" I used the command 'kustomize edit fix' and it updated the file to look like this

patchesStrategicMerge is deprecated updating to patches

---

Makefile

Allow users to specify non-default `NAMESPACE` for `make undeploy`
The command `NAMESPACE=awesomegalaxy make undeploy` does not works as expected after `git checkout .`.
```bash
$ NAMESPACE=awesomegalaxy make deploy
cd config/manager && /home/kuro/work/kurokobo/galaxy-operator/bin/kustomize edit set image controller=quay.io/ansible/galaxy-operator:2024.4.3-10-ga21c706
cd config/default && /home/kuro/work/kurokobo/galaxy-operator/bin/kustomize edit set namespace awesomegalaxy
/home/kuro/work/kurokobo/galaxy-operator/bin/kustomize build config/default | kubectl apply -f -
namespace/awesomegalaxy created
...
$ git checkout .
Updated 2 paths from the index
$ NAMESPACE=awesomegalaxy make undeploy
/home/kuro/work/kurokobo/galaxy-operator/bin/kustomize build config/default | kubectl delete -f - …
```

fix: make undeploy to respect user-provided namespace

---

config/crd/bases/galaxy_v1beta1_galaxy_crd.yaml
roles/backup/templates/backup-content-k8s-job.yaml.j2
roles/restore/templates/restore-content-k8s-job.yaml.j2

Fixes Backups to include the signing secret.
Explicitly set directories in /var/lib/pulp/ to avoid permissions issues with .gnupg directory.

fixing signing-secret backup

---

roles/galaxy-api/templates/galaxy-api.deployment.yaml.j2
roles/galaxy-content/templates/galaxy-content.deployment.yaml.j2
roles/galaxy-worker/templates/galaxy-worker.deployment.yaml.j2

The signing secret and signing configmap's names were incorrectly hardcoded and would not use a user-provided resource unless the naming was the hardcoded value.
This PR fixes the resources to be named according to what the user provides for secret and configmap values.

fixing signing scripts and configmap to use user-provided names

---

roles/postgres/tasks/main.yml

When using an external database then the `Check PostgreSQL status` task is waiting and failing because there's no such stateful resource
This was introduced in 2641fcd
```console
TASK [Check PostgreSQL status] ********************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check '_pg_sts_status['resources'][0]['status']['availableReplicas'] == _pg_sts_status['resources'][0]['status']['replicas']' failed. The error was: error while evaluating conditional (_pg_sts_status['resources'][0]['status']['availableReplicas'] == _pg_sts_status['resources'][0]['status']['replicas']): list object has no element 0"}
```

postgres: Wait for stateful on managed db

---

roles/galaxy-config/tasks/get_node_ip.yml

fixes #122 
This PR corrects `when` statement to be `true` if `ingress_tls_secret` OR `route_tls_secret` is specified.
Tested CR that includes following snippet:
```yaml
apiVersion: galaxy.ansible.com/v1beta1
kind: Galaxy
metadata:
name: galaxy
spec:
image: quay.io/ansible/galaxy-ng
image_version: b7b07e96
image_web: quay.io/ansible/galaxy-ui
image_web_version: 19fd5a2b
ingress_type: ingress
ingress_tls_secret: galaxy-secret-tls
hostname: galaxy.example.com
pulp_settings:
galaxy_collection_signing_service: ""
galaxy_container_signing_service: ""
token_auth_disabled: "True"
galaxy_enable_unauthenticated_collection_access: "True"
galaxy_enable_unauthenticated_collection_download: "True"
...
```
```bash
$ kubectl -n galaxy exec deployment/galaxy-api -- cat /etc/pulp/settings.py | grep http …
```

fix: correct remote scheme to https when  any tls secret is specified

---

.ci/assets/kubernetes/galaxy-external-database.secret.yaml
.ci/scripts/backup_and_restore.sh
.ci/scripts/prepare-external-database.sh
.github/workflows/ci.yml
.github/workflows/pr.yml
.gitleaks.toml
config/samples/galaxy_v1beta1_galaxy_cr.galaxy.externaldb.ci.yaml
roles/restore/tasks/deploy_galaxy.yml
up.sh

This adds a new CI scenario for deploying the galaxy operator with an external database.
The external database is just a postgresql container running on the host via docker (like azurite and minio).
The postgresql secret is created and referenced in the externaldb CI CRD.
The postgresql container is mapped on port 5555 on the host to avoid conflicting with existing postgresql instance running by default.

ci: Add scenario for external database

---

config/crd/bases/galaxy_v1beta1_galaxyrestore_crd.yaml
config/manifests/bases/galaxy-operator.clusterserviceversion.yaml
roles/restore/defaults/main.yml
roles/restore/tasks/deploy_galaxy.yml

Port of restore overrides PR from the awx-operator:
* https://github.com/ansible/awx-operator/pull/1862
There are often times where you might want to override specific parameters on the Galaxy spec when restoring from a backup. One such case is when you want to extend the database PVC size.  
To extend the storage size of your postgres PVC, with this change, you can now:
1. Create an GalaxyBackup
2. Create an GalaxyRestore with a spec_overrides entry for `spec_overrides.postgres_storage_requirements.requests: 110Gi` on your GalaxyRestore object
3. The new deployment will have any spec_overrides preferentially included on the new Galaxy CR spec.
- New or Enhanced Feature

Add support for spec overrides when restoring Galaxy

---

roles/backup/README.md
roles/backup/defaults/main.yml

If we have default value for admin password and postgres configuration secrets then the backup CR status will be updated with those names during the reconciliation loop.
This breaks the backup/restore worfklow when using custom secret.
- 1st backup execution:
`"databaseConfigurationSecret": "galaxy-external-database"`
- 2nd backup exection:
`"databaseConfigurationSecret": "example-galaxy-postgres-configuration"`
Later the restore will fail because the new deployment won't use the correct secret name.
This also removes the postgres_configuration_secret reference from the backup README because such parameter doesn't exist on this CRD.

backup: Remove default values for secret

---

roles/galaxy-api/templates/galaxy-api.deployment.yaml.j2
roles/galaxy-content/templates/galaxy-content.deployment.yaml.j2
roles/galaxy-status/tasks/main.yml
roles/galaxy-web/templates/galaxy-web.deployment.yaml.j2
roles/galaxy-worker/templates/galaxy-worker.deployment.yaml.j2
roles/postgres/tasks/main.yml
roles/postgres/tasks/upgrade_postgres.yml
roles/postgres/templates/postgres.yaml.j2
roles/redis/templates/redis.deployment.yaml.j2

This updates the apiVersion from v1 to apps/v1 for deployment and statefulset resources to avoid issues such as when kubevirt is installed on a k8s cluster.
Closes: #128

Update apiVersion for deployment/statefulset

---

roles/backup/templates/backup-content-k8s-job.yaml.j2

This PR fixes some backup errors for galaxy.
This is what I see in the content pod after uploading 2 collections, everything looks good here:
```
sh-4.4$ ls -la /var/lib/pulp/     
total 4
drwxrwsrwx. 4 root       root   30 Jun 14 13:41 .
drwxr-xr-x. 1 root       root 4096 Jun 14 04:21 ..
drwxr-sr-x. 3 1000670000 root   22 Jun 14 13:52 media
drwxr-sr-x. 3 1000670000 root   49 Jun 14 13:54 tmp
sh-4.4$ ls -la /var/lib/pulp/media/artifact/
total 0
drwxr-sr-x. 4 1000670000 root 26 Jun 14 13:54 .
drwxr-sr-x. 3 1000670000 root 22 Jun 14 13:52 ..
drwxr-sr-x. 2 1000670000 root 76 Jun 14 13:54 8c
drwxr-sr-x. 2 1000670000 root 76 Jun 14 13:52 de
```
Permissions on the artifact itself is 0644, the artifact directory is 2755
So the media and tmp directories are good.  But backups expect artifacts and …

Copy the correct path for artifacts and check if it exists first

---

roles/restore/tasks/secrets.yml

Fixes the following bug during pg restores...
```
[11:06](https://redhat-internal.slack.com/archives/DD5STBGQN/p1718809616543609)
TASK [Restore database dump to the new postgresql container] ********************************
fatal: [localhost]: FAILED! => {"changed": true, "rc": 1, "return_code": 1, "stderr": "pg_restore: error: could not translate host name \"mygalaxy-postgres-15\" to address: Name or service not known\nbash: line 12: 34 Terminated sleep 60\n", "stderr_lines": ["pg_restore: error: could not translate host name \"mygalaxy-postgres-15\" to address: Name or service not known", "bash: line 12: 34 Terminated sleep 60"], "stdout": "Migrating data from old database...\nkeepalive_pid: 32\n", "stdout_lines": ["Migrating data from old database...", "keepalive_pid: 32"]}
```
Now …

Set new db_secret_name value for managed pg restores

---

roles/galaxy-api/templates/galaxy-api.deployment.yaml.j2

Resource sync job needed for integration with other components.  This will be a noop if RESOURCE_SERVER_URL is not defined.
```
```

Add initContainer for creating resource sync job

---

roles/galaxy-status/tasks/main.yml

The `deployedVersion` status was present in the galaxy CRD and CSV file but the `k8s_status` task to update the version status wasn't doing anything.
This uses the galaxy version collected from the pulp status API endpoint.

status: Add deployed version field

---

roles/galaxy-config/tasks/combine_galaxy_settings.yml
roles/galaxy-config/tasks/get_node_ip.yml

Always set container token auth settings, even in the auth secret is generated
(enabling debug-3ci)

Always set container token auth settings, even in the auth secret is generated

---

roles/galaxy-config/tasks/combine_galaxy_settings.yml

If the `pulp_settings.content_origin` is set by the user, we should set the temp content_orgin var so that it is used in the token_server_dict var, otherwise if the user sets this variable it will fail on the task that sets that dict.
Without this, the following error will be seen:
```
TASK [Set token_server and other container default settings] ******************************** 
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'content_origin' is undefined\n\nThe error appears to be in '/opt/ansible/roles/galaxy-config/tasks/combine_galaxy_settings.yml': line 41, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set token_server and other …
```

Content origin temp var should be the same for both scenarios

---

config/crd/bases/galaxy_v1beta1_galaxy_crd.yaml
config/crd/bases/galaxy_v1beta1_galaxyrestore_crd.yaml
config/manifests/bases/galaxy-operator.clusterserviceversion.yaml

This param was added to the Galaxy CRD by mistake instead of the GalaxyRestore CRD.

Move force_drop_db param to restore CRD where it belongs

---

config/crd/bases/galaxy_v1beta1_galaxy_crd.yaml
config/manifests/bases/galaxy-operator.clusterserviceversion.yaml

There's no "built in" logic for clustering or sentinel for Hub's internal redis.  Horizontal scaling (i.e., increasing replicas) does not automatically distribute cache data across the pods. Each replica would have its own independent cache, which means one pod won’t have access to the data cached by another pod. These inconsistencies could cause issues. 
Instead, you would need to use Redis Cluster for true horizontal scaling with distributed caching. Configuring an external Redis should be a future RFE to satisfy this request.
As a result, we should deprecate this field so it does not confuse users.

Deprecate redis.replicas as it is intentionally hardcoded to 1

---

.ci/scripts/backup_and_restore.sh
.ci/scripts/galaxy_ng-tests.sh
.ci/scripts/galaxy_tests.sh
.github/workflows/ci.yml
.github/workflows/pr.yml
.github/workflows/stage.yaml
ansible-down.sh
ansible-up.sh
dev/admin-password-secret.yml
dev/galaxy.cr.yml
docs/contributing.md
docs/development.md

Eventually, I want to rewrite our CI (which currently depends on the up.sh and down.sh committed to the repo), then add the scripts I just shared here instead.  That way the galaxy-operator will be exactly like the other 5 operators.
But for now, I'll just add these scripts with the `ansible-` prefix so they don't conflict.
Usage:
```
export QUAY_USER=username
export NAMESPACE=galaxy
export TAG=test
./ansible-up.sh
```

Add Development scripts with ansible- prefix for now

---

roles/galaxy-route/tasks/main.yml

This change the api version from v1 to route.openshift.io/v1 to avoid issue when using kubevirt.
All other tasks related to `kind: Route` are already using this.
This is similar to what was done in 4b526eb.

route: Use explicit api version

---

roles/common/tasks/check_existing.yml

We should add a check loop for the upgrade test script, but we should also make sure this doesn't fail in the hub operator by checking that the status exists first.
```
[common : Set previous_version version based on automationhub CR version status] ***\r\n\u001b[1;30mtask path: /opt/ansible/roles/common/tasks/check_existing.yml:12\u001b[0m\n\u001b[0;31mfatal: [localhost]: FAILED! => {\"msg\": \"The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'deployedVersion'
```
```
```

Check that deployedVersion status is defined to avoid failures

---

roles/common/tasks/check_existing.yml

```
The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'deployedVersion'
```
Fixes https://issues.redhat.com/browse/AAP-33810

Check if deployedVersion is defined in status before eval

---

config/crd/bases/galaxy_v1beta1_galaxy_crd.yaml
config/manifests/bases/galaxy-operator.clusterserviceversion.yaml

Add back force_drop_db to avoid validation error upon upgrade.
If a user had force_drop_db parameter set in a prior version, upon upgrade this would throw a validation error:
```
strict decoding error: unknown field "spec.force_drop_db"
```

Add back force_drop_db to avoid validation error upon upgrade

---

roles/galaxy-api/tasks/resource_configuration.yml

environment does not get pass into command for k8s exec
Related: https://github.com/ansible/awx-operator/pull/1977
Thankfully, we've already done this in the eda operator:
* https://github.com/ansible/eda-server-operator/blob/main/roles/eda/tasks/create_admin_user.yml#L22

Fix disable reverse sync on mgmt command

---

roles/common/tasks/check_existing.yml

This happens when the `deployedVersion` label is not set on the hub CR.
```
[localhost]: FAILED! => {\"msg\": \"The conditional check 'previous_version is version(gating_version, '<')' failed. The error was: Version comparison: 'previous_version' is undefined\\n\\nThe error appears to be in '/opt/ansible/roles/common/tasks/check_existing.yml': line 22, column 7, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n\\n    - name: Set upgraded_from to previous_version ({{ previous_version }}) if older than gating_version ({{ gating_version }})
```
```
```

Check that previous_version is defined before continuing

---

.github/workflows/ci.yml
.github/workflows/pr.yml
roles/common/tasks/main.yml

Pin the git hash as the tag for the galaxy-operator image in CI.
```
```

Use CI image for this PR to test with

---

roles/common/tasks/check_existing.yml
roles/common/tasks/main.yml
roles/galaxy-status/tasks/main.yml
roles/galaxy-status/tasks/version.yml

If an existing deployment doesn't have the deployedVersion status set then we can force this to be set at the beginning of the operator execution.
This will help determine if there's an upgrade needed or not.

Add deployedVersion if not set

---

roles/common/tasks/main.yml

That way we set the postgres facts needed by combine_galaxy_settings, called by check_existing tasks.
Fixes https://issues.redhat.com/browse/AAP-33865

Include postgres_configuration before check_existing tasks

---

roles/common/tasks/check_existing.yml

Remove char in task name var preventing the variable from being evaluated
Error:
```
 TASK [Set previous_version version based on {{ deployment_type }} CR version status] ******************************** 
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'existing_deployment.resources | length > 0' failed. The error was: error while evaluating conditional (existing_deployment.resources | length > 0): 'dict object' has no attribute 'resources'\n\nThe error appears to be in '/opt/ansible/roles/common/tasks/check_existing.yml': line 34
```

Remove char in task name var preventing the variable from being evaluated

---

playbooks/galaxy.yaml

Adds sslrootcert in the database options pointing to the volume mount of the bundle_cacert_secret. This allows a custom CA to be used if sslmode is set to `verify-ca` or `verify-full` in the postgres_configuration_secret.
Issue: AAP-32390

Specify sslrootcert in database options

---

roles/backup/defaults/main.yml
roles/backup/tasks/custom_resource.yml
roles/restore/tasks/init.yml

Backup should specify the postgres_configuration parameter, not database.database_secret
* database.database_secret is the new syntax that is currently used in eda-server-operator, but that has not yet been added to the galaxy CRD schema.
Without this change, the cr_object in the backup PVC looks like this:
```
sh-4.4$ cat cr_object 
spec:
admin_password_secret: myaap-galaxy-admin-password
database: {database_secret: myaap-galaxy-postgres-configuration}
db_fields_encryption_secret: myaap-galaxy-db-fields-encryption
file_storage_access_mode: ReadWriteMany
file_storage_size: 10Gi
file_storage_storage_class: nfs-local-rwx
force_drop_db: false
ingress_type: Route
no_log: false
postgres_configuration_secret: myaap-galaxy-postgres-configuration  # This should be database.database_secret instead …
```

Backup should specify the postgres_configuration parameter, not database.database_secret

---

roles/restore/tasks/secrets.yml

In the case where `spec_overrides.postgres_configuration_secret` is set on the GalaxyRestore object, we need to check it before setting the `db_secret_name` variable in the restore role or else the pg_restore step fails because it is pointed to the wrong db secret.

Check spec_overrides when setting db_secret_name variable for restores

---

config/manifests/bases/galaxy-operator.clusterserviceversion.yaml

Rather than using the text field then we can use the kubernetes PersistentVolumeClaim descriptor so it resolves the associated object from the UI.
Before
After

csv: Use PersistentVolumeClaim for file storage

---

roles/galaxy-api/templates/redirect-page.configmap.html.j2

- without this trailing slash, user will currently see a 404
For example, https://galaxy-host.openshift.com/api/galaxy will not resolve, but https://galaxy-host.openshift.com/api/galaxy/ will.
We should also fix the nginx.conf long-term so that it works without the slash too.

Add trailing slash to Galaxy API redirect link

---

config/manager/manager.yaml

Closes https://issues.redhat.com/browse/AAP-37931
Reducing the galaxy operator's resource limit to the best minimum value that doesn't makes the operator OOMkilled.

galaxy operator: reduce resource limit

---

config/crd/bases/galaxy_v1beta1_galaxy_crd.yaml
config/crd/bases/galaxy_v1beta1_galaxybackup_crd.yaml
config/crd/bases/galaxy_v1beta1_galaxyrestore_crd.yaml

Remove x-kubernetes-preserve-unknown-fields field from schema so that users can run:
```
oc explain Galaxy.spec
```
When I remove this line under Galaxy.spec in the CRD, the oc explain works:
```
x-kubernetes-preserve-unknown-fields: true
```
When this line is removed, or set to false (default), then parameters that are not explicitly defined on the CRD schema will not be accepted and the k8s validator will automatically (and silently) omit any parameters that it does not know about when the CRD is modified / created.
In the case of Galaxy, I think that should be fine because all accepted params are defined in the CRD schema already.
The `spec.extra_settings` param will still set that preserve-unknown-fields config to true for just extra_settings, so that's OK.

Remove x-kubernetes-preserve-unknown-fields field from schema so explain params work

---

dev/galaxy.cr.yml
galaxy-cr.yaml

The ansible_up.sh script uses the NAMESPACE environment variable to create resources but the dev CR hardcodes galaxy as namespace value. So when using a different value than NAMESPACE=galaxy for that script then the operator fails because the signing script and secret (and probably other resources) are created into a different namespace than the operator.
```console
TASK [Set environment variable for the GPG key ID] ********************************
fatal: [localhost]: FAILED! => {"msg": "The input for the community.crypto.gpg_fingerprint filter must be a string; got <class 'ansible.template.AnsibleUndefined'> instead"}
```

Remove namespace on dev Custom Resource

---

ansible-up.sh

Switch context to namespace provided in ansible-up.sh so that it is used when creating the galaxy CR later on in the up.sh script.

Switch context to namespace provided in ansible-up.sh

---

config/crd/bases/galaxy_v1beta1_galaxy_crd.yaml
dev/galaxy.cr.yml
roles/redis/defaults/main.yml
roles/redis/tasks/main.yml
roles/redis/templates/redis.deployment.yaml.j2

Closes: https://issues.redhat.com/browse/AAP-20309
Set condition on redis pvc.
This PR makes it possible to reduce the number of PVC's required to deploy Galaxy by making redis data persistence optional. 
To do so, modify your Galaxy spec to add is param:
```
spec:
redis_data_persistence: false
```
It is still recommended to set this to true, and having it backed by a PVC should make scaling up and down pods a bit smoother.  But the redis cache should be recreated if the redis pod should go down, so this is acceptable for demo/test environments.

AAP-20309 conditional redis pvc

---

roles/redis/tasks/main.yml
roles/redis/templates/redis.deployment.yaml.j2

Fixes error:
```
`task path: /opt/ansible/roles/redis/tasks/main.yml:2\u001b[0m\n\u001b[0;31mfatal: [localhost]: FAILED! => {\"msg\": \"The conditional check 'redis_data_persistence is true' failed. The error was: template error while templating string: no test named 'true'. String: {% if redis_data_persistence is true %} True {% else %} False {% endif %}\\n\\nThe error appears to be in '/opt/ansible/roles/redis/tasks/main.yml'`
```
Before this change, fresh installs were failing.

Fix redis_data_persistence conditional

---

config/crd/bases/galaxy_v1beta1_galaxy_crd.yaml
config/manifests/bases/galaxy-operator.clusterserviceversion.yaml
roles/common/defaults/main.yml
roles/common/tasks/idle_deployment.yml
roles/common/tasks/main.yml
roles/common/tasks/postgres_configuration.yml
roles/postgres/tasks/main.yml

This PR adds the ability to scale down your Galaxy Deployments StatefulSets and subsequently your pods to save on resource utilization if you have scheduled downtime.  
This can also be useful for scaling down the pods when upgrading the PostgreSQL database when you have an external database configured.  This way you won't have requests hitting the database during scheduled maintenance when the DB is being upgraded.
```
---
apiVersion: galaxy.ansible.com/v1beta1
kind: Galaxy
metadata:
name: galaxy
spec:
idle_deployment: false   # set to true to scale down all pods
```

Feature: Add ability to idle Galaxy deployments and statefulsets

---

roles/common/tasks/azure-storage-configuration.yml
roles/common/tasks/s3-storage-configuration.yml

Private Automation Hub installation with S3 failing with following error
```
2025-02-28T02:11:09.543211999Z  TASK [merge s3_access_key_id with settings] ******************************** 
2025-02-28T02:11:09.543211999Z ESC[0;31mfatal: [localhost]: FAILED! => {"msg": "|combine expects dictionaries, got \"{'AWS_ACCESS_KEY_ID': '**************\\n' }\""}ESC[0m
```
Reason for this problem is incorrect way of setting a variable fact as `string` https://github.com/ansible/galaxy-operator/blob/main/roles/common/tasks/s3-storage-configuration.yml#L152-L155 which per the playbook should be a `dictionary` because `combine` filter works on dictionaries https://github.com/ansible/galaxy-operator/blob/main/roles/common/tasks/s3-storage-configuration.yml#L180-L183
This problem is same for azure storage …

fix incorrect format of dict with set_fact

---

roles/restore/defaults/main.yml
roles/restore/tasks/postgres.yml

Restores are currently obtaining the previous deployment's postgres config name resulting in failed restores.
This fixes restores to use the correct postgres config.
This also adds a pg_isready command to make sure postgres is ready first for data migration.

Fix restore role postgres config and race conditions

---

config/default/kustomization.yaml
config/policies/kustomization.yaml
config/policies/storage_type_binding.yaml
config/policies/storage_type_validation.yaml
config/samples/galaxy_v1beta1_galaxy_cr.ci.yaml
config/samples/galaxy_v1beta1_galaxy_cr.galaxy-demo.yaml
config/samples/galaxy_v1beta1_galaxy_cr.galaxy.ci.yaml
config/samples/galaxy_v1beta1_galaxy_cr.galaxy.externaldb.ci.yaml
config/samples/galaxy_v1beta1_galaxy_cr.galaxy.s6.ci.yaml
config/samples/galaxy_v1beta1_galaxy_cr.molecule.ci.yaml
config/samples/galaxy_v1beta1_galaxy_cr.s6.ci.yaml

https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/
closes AAP-43765
```
galaxy-operator on  policies [$] via 🐍 v3.11.11 (venv) 
❯ kubectl apply -f config/samples/galaxy_v1beta1_galaxy_cr.ci.yaml             
The galaxies "example-galaxy" is invalid: : ValidatingAdmissionPolicy 'galaxy-operator-storage-type-validation' with binding 'galaxy-operator-storage-type-binding' denied request: storage_type should not be empty
galaxy-operator on  policies [$!] via 🐍 v3.11.11 (venv) 
❯ kubectl apply -f config/samples/galaxy_v1beta1_galaxy_cr.ci.yaml
The galaxies "example-galaxy" is invalid: : ValidatingAdmissionPolicy 'galaxy-operator-storage-type-validation' with binding 'galaxy-operator-storage-type-binding' denied request: please specify a rwx …
```

Adding validation policies

---

config/crd/bases/galaxy_v1beta1_galaxy_crd.yaml
roles/galaxy-api/README.md
roles/galaxy-api/defaults/main.yml
roles/galaxy-api/templates/galaxy-api.deployment.yaml.j2
roles/galaxy-content/README.md
roles/galaxy-content/defaults/main.yml
roles/galaxy-content/templates/galaxy-content.deployment.yaml.j2
roles/galaxy-route/defaults/main.yml
roles/galaxy-web/templates/galaxy-web.configmap.yaml.j2

not timing out before undercuts usefulness of our log-traceback-middleware in django-ansible-base that logs a traceback from requests that get timed out -- because uwsgi or gunicorn has to send the timeout signal to the worker handling the request. Also leads to issues where requests that envoy has already timed out are filling up queues of the workers of the components.
Also, configure nginx to return a 503 if WSGI server doesn't respond.
co-authored by: @kdelee

Timeout before the openshift route times out

---

playbooks/check_pulp_dependency_versions.yml
playbooks/galaxy.yaml

If upgrading from a version of galaxy with pulp_ansible < 0.23 to one with 0.23+ (like 0.25 for example in the latest), there are some incompatibility issues that require use to scale down the galaxy deployments before migrations will pass in the new galaxy api container.
Specifically, when the new galaxy pod comes up, if fails when trying to run the migrations with the following error:
```
$ oc logs -f galaxy-api-585bbbfdbf-vm8bp -c run-migrations
...
RuntimeError: Incompatible versions detected (ansible >= 0.23.0 needed):
- 'ansible'='0.20.11' with content server '41@existing-galaxy-content-6d5f569bf-5zwl4'
- 'ansible'='0.20.11' with content server '46@existing-galaxy-content-6d5f569bf-5zwl4'
- 'ansible'='0.20.11' with pulp worker '1@existing-galaxy-worker-d787d569d-d56zf'
- …
```

Conditionally cycle deployments if upgrading  pulp_ansible < 0.23

---

docs/user-guide/content-signing.md
mkdocs.yaml

Adds new documentation for configuring content signing in the galaxy-operator.
This includes:
- A new  file in the  directory.
- An update to the  file to include the new documentation in the navigation.

feat(docs): add content signing documentation
