ansible/galaxy-operator

.github/workflows/stage.yaml

Previously, the script name ref was wrong and the output wasn't getting captured in a variable.

Correctly set cal-ver output in stage.yml

---

.github/workflows/stage.yaml

Fix path to calver script for stage.yml

---

.github/workflows/stage.yaml

Add working-directory to path

---

.readthedocs.yaml

adding nodejs dependency for search plugin

adding nodejs dependency for search plugin

---

Makefile

Fixing image name in the Makefile

fixing image name in makefile

---

README.md
config/manifests/bases/galaxy-operator.clusterserviceversion.yaml
mkdocs.yaml

updating README

---

README.md
config/manifests/bases/galaxy-operator.clusterserviceversion.yaml
docs/build.md
mkdocs.yaml

adding search to readthedocs
updating image width and centering
updating READMEs
streamlining readthedocs plugins

updating README and Docs

---

README.md

Fixing path to logo for README/docs.

fixing logo image path

---

README.md
images
mkdocs.yaml

adding symlink to images directory for readthedocs

adding symlink to images directory for readthedocs

---

README.md
images

reverting image path and removing symlink

reverting image path and removing symlink

---

config/manager/manager.yaml

Removing this comment.  Mostly checking if ci passes now that https://github.com/ansible/galaxy_ng/pull/2105 has merged, but we can merge this.

Remove unnecessary comment

---

roles/common/vars/main.yml

Wrong path... it should be /venv/bin

Fix entrypoint path for pulpcore scripts

---

Makefile
config/crd/bases/galaxy_v1beta1_galaxybackup_crd.yaml
config/crd/bases/galaxy_v1beta1_galaxyrestore_crd.yaml
config/default/kustomization.yaml
config/manifests/bases/galaxy-operator.clusterserviceversion.yaml
config/samples/galaxy_v1beta1_galaxy_cr.galaxy.azure.ci.yaml
config/samples/galaxy_v1beta1_galaxy_cr.galaxy.ci.yaml
config/samples/galaxy_v1beta1_galaxy_cr.galaxy.ocp.ci.yaml
config/samples/galaxy_v1beta1_galaxy_cr.galaxy.s3.ci.yaml
config/samples/galaxy_v1beta1_galaxy_cr.galaxy.s6.ci.yaml
config/samples/galaxy_v1beta1_galaxybackup_cr.default.yaml
config/samples/galaxy_v1beta1_galaxyrestore_cr.default.yaml
config/samples/kustomization.yaml
playbooks/galaxy.yaml
roles/galaxy-api/templates/galaxy-api.deployment.yaml.j2
roles/galaxy-route/tasks/load_routes.yml
roles/galaxy-status/tasks/main.yml
roles/galaxy-web/tasks/main.yml
roles/galaxy-web/templates/galaxy-web.configmap.yaml.j2
roles/galaxy-web/templates/galaxy-web.deployment.yaml.j2

Updating api root
Updating csv fields

Fix galaxy api root and update csv fields

---

.github/workflows/ci.yml
.github/workflows/pr.yml

ci: Pin on kubernetes 1.28

---

roles/backup/templates/azure_secret.yaml.j2
roles/restore/templates/azure_secret.yaml.j2

Prevent undefined variable error during GalaxyBackup/GalaxyRestore.
See #110

Fix issue #110

---

config/crd/bases/galaxy_v1beta1_galaxy_crd.yaml
roles/common/tasks/check_existing.yml
roles/common/tasks/main.yml
roles/common/vars/main.yml
roles/galaxy-status/tasks/main.yml

adding logic to check existing deployment versions

adding logic to check existing deployment versions

---

roles/common/tasks/check_existing.yml

Removing redundant conditional

removing redundant conditional

---

roles/common/tasks/check_existing.yml

Instead of checking the CR for deployed version in the status field then we'll check existing deployment.

Check API deployment for deployed version

---

config/crd/bases/galaxy_v1beta1_galaxy_crd.yaml
roles/galaxy-api/templates/galaxy-api.deployment.yaml.j2

removing default blank value for public_base_url
this fixes the behavior of the redirect page for aap

removing default blank value for public_base_url

---

config/crd/bases/galaxy_v1beta1_galaxy_crd.yaml
roles/common/defaults/main.yml
roles/redis/templates/redis.deployment.yaml.j2

fixing redis template to use set replica values (currently hardcoded to 1)

fixing redis template to use set replica values

---

.github/workflows/pr.yml
config/crd/bases/galaxy_v1beta1_galaxy_crd.yaml
config/manifests/bases/galaxy-operator.clusterserviceversion.yaml
roles/common/defaults/main.yml
roles/common/tasks/idle_deployment.yml
roles/common/tasks/main.yml
roles/common/tasks/postgres_configuration.yml
roles/postgres/tasks/main.yml

Couples with https://github.com/ansible/galaxy-operator/pull/178 to test idle_deployment functionality
```
```

Idle deployment CI Check

---

roles/galaxy-route/templates/galaxy.ingress.yaml.j2

Fix Route TLS termination mechanism

---

roles/backup/templates/event.yaml.j2
roles/galaxy-api/templates/redirect-page.configmap.html.j2
roles/postgres/templates/event.yaml.j2
roles/restore/templates/event.yaml.j2

fixing quotes on namespace to support namespace names with only numbers

fixing quotes on namespace to support namespace names with only numbers
